### ISSUE TITLE
Add pojavlauncher support 

### ISSUE THREAD

**Issue by miggythewriter** [Aeroshide/SpecSpoof#4]
Basically when I try to load it, it's able to get to the Mojang screen and it would crash, please make this mod compatible 🙏🏻

**Comment by Aeroshide** [comment]
Are you able to send a crash report?, i am unable to use pojav launcher as i don't use android. Maybe with that i can figure out how to make it work.

**Comment by miggythewriter** [comment]
> Are you able to send a crash report?, i am unable to use pojav launcher as i don't use android. Maybe with that i can figure out how to make it work.

Weirdly the mod doesn't seem to leave a crash report I do have the latestlog if you want it?

**Comment by Aeroshide** [comment]
> > Are you able to send a crash report?, i am unable to use pojav launcher as i don't use android. Maybe with that i can figure out how to make it work.
> 
> Weirdly the mod doesn't seem to leave a crash report I do have the latestlog if you want it?

yeah yeah, that could work

**Comment by miggythewriter** [comment]
> > > Are you able to send a crash report?, i am unable to use pojav launcher as i don't use android. Maybe with that i can figure out how to make it work.
> > 
> > 
> > Weirdly the mod doesn't seem to leave a crash report I do have the latestlog if you want it?
> 
> yeah yeah, that could work

[latestlog.txt](https://github.com/user-attachments/files/16301325/latestlog.txt)
Here is the latestlog

**Comment by Aeroshide** [comment]
Thanks, I have done some minor changes to the mod to make it support Pojav, since i don't have the unit to test on. are you willing to try this test build to verify if the implementation is working?. thanks in advance

[SpecSpoof-1.3.1-dirty.jar](https://cdn.discordapp.com/attachments/406063528819294228/1263794037144424529/SpecSpoof-1.3.1-dirty.jar?ex=669b876a&is=669a35ea&hm=10c9e37768b9aa616381b84249c8fd19af7fd25cbaf038252e02bedc2cc9fa5d&)

**Comment by miggythewriter** [comment]
> Thanks, I have done some minor changes to the mod to make it support Pojav, since i don't have the unit to test on. are you willing to try this test build to verify if the implementation is working?. thanks in advance
> 
> [SpecSpoof-1.3.1-dirty.jar](https://cdn.discordapp.com/attachments/406063528819294228/1263794037144424529/SpecSpoof-1.3.1-dirty.jar?ex=669b876a&is=669a35ea&hm=10c9e37768b9aa616381b84249c8fd19af7fd25cbaf038252e02bedc2cc9fa5d&)

Hell yeah I'll reply if there are any issues

**Comment by miggythewriter** [comment]
> Thanks, I have done some minor changes to the mod to make it support Pojav, since i don't have the unit to test on. are you willing to try this test build to verify if the implementation is working?. thanks in advance
> 
> [SpecSpoof-1.3.1-dirty.jar](https://cdn.discordapp.com/attachments/406063528819294228/1263794037144424529/SpecSpoof-1.3.1-dirty.jar?ex=669b876a&is=669a35ea&hm=10c9e37768b9aa616381b84249c8fd19af7fd25cbaf038252e02bedc2cc9fa5d&)

It works thank you 🙏🏻
![2024-07-19_12 08 34](https://github.com/user-attachments/assets/1deb6c37-d78a-4359-a42c-2ea44ca77520)
![2024-07-19_12 08 37](https://github.com/user-attachments/assets/13f19451-5512-451c-8553-8475954bc61d)
![2024-07-19_12 09 53](https://github.com/user-attachments/assets/d4512e77-9162-4c29-b60c-f6702045104a)

**Comment by Aeroshide** [comment]
Awesome, closing this after new commit. thank you for helping me testing it out!,

**Comment by miggythewriter** [comment]
> Awesome, closing this after new commit. thank you for helping me testing it out!,

One last thing is there a way to change this?
![2024-07-19_12 36 46](https://github.com/user-attachments/assets/85d5a1ee-128b-4a7e-9147-69524e09392e)

**Comment by Aeroshide** [comment]
> > Awesome, closing this after new commit. thank you for helping me testing it out!,
> 
> One last thing is there a way to change this? ![2024-07-19_12 36 46](https://private-user-images.githubusercontent.com/100645830/350476909-85d5a1ee-128b-4a7e-9147-69524e09392e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MDc3NjYsIm5iZiI6MTcyMTQwNzQ2NiwicGF0aCI6Ii8xMDA2NDU4MzAvMzUwNDc2OTA5LTg1ZDVhMWVlLTEyOGItNGE3ZS05MTQ3LTY5NTI0ZTA5MzkyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNjQ0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmJjMTY1ZjU0YjA4Y2RjMTJhMGIwZGE5ZmNhNzg4Yzg1MDdhNjdkNmY5OGI4MzRjZGY5MGZlZGUzYzYyZDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.go4Vlkn5IiNvpWk271eAwppOc6QLBXHL_AInciRmkjs)

You just write the values on the text field, if somehow you cant, you can access the config folder (.minecraft/config) and look for SpecSpoof.json

**Comment by miggythewriter** [comment]
> > > Awesome, closing this after new commit. thank you for helping me testing it out!,
> > 
> > 
> > One last thing is there a way to change this? ![2024-07-19_12 36 46](https://private-user-images.githubusercontent.com/100645830/350476909-85d5a1ee-128b-4a7e-9147-69524e09392e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MDc3NjYsIm5iZiI6MTcyMTQwNzQ2NiwicGF0aCI6Ii8xMDA2NDU4MzAvMzUwNDc2OTA5LTg1ZDVhMWVlLTEyOGItNGE3ZS05MTQ3LTY5NTI0ZTA5MzkyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQxNjQ0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmJjMTY1ZjU0YjA4Y2RjMTJhMGIwZGE5ZmNhNzg4Yzg1MDdhNjdkNmY5OGI4MzRjZGY5MGZlZGUzYzYyZDFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.go4Vlkn5IiNvpWk271eAwppOc6QLBXHL_AInciRmkjs)
> 
> You just write the values on the text field, if somehow you cant, you can access the config folder (.minecraft/config) and look for SpecSpoof.json

Ohh it always seems to go back to the original it's probably not the mod issue but pojav's issue
