### ISSUE TITLE
Cant edit GPU driver in pojavlauncher version

### ISSUE THREAD

**Issue by Idkwoeer** [Aeroshide/SpecSpoof#5]
Basically I heard that this mod works now in pojavlauncher and I was using when I notice that the GPU driver doesn't change when I edit it it goes back please fix

**Comment by Aeroshide** [comment]
is it only GPU driver or is there anything else? is GPU vendor changeable?

**Comment by Idkwoeer** [comment]
> is it only GPU driver or is there anything else? is GPU vendor changeable?

Yes it is only GPU driver everything else works fine

**Comment by Aeroshide** [comment]
> > is it only GPU driver or is there anything else? is GPU vendor changeable?
> 
> Yes it is only GPU driver everything else works fine

Hey, sorry for taking so long. i have found a negligible workaround for arm platforms, would you mind testing it again?

[specspoof-1.3.1-dirty2](https://cdn.discordapp.com/attachments/406063528819294228/1263952809691447457/SpecSpoof-1.3.1-dirty2.jar?ex=669c1b48&is=669ac9c8&hm=ff8682de970dfb736defaedf2d4904d2a9eeacf11aaa58bb2a97d330df28b81f&)

**Comment by Aeroshide** [comment]
All pojav related issues should be fixed in the latest update on [Modrinth](https://modrinth.com/mod/specspoof) as i now understood how the platform work, this issue will be closed.
